version: "3.5"
services:
  redis:
    image: redis:6.2.2-alpine
    container_name: demo_redis
    ports:
      - 5432:5432

  demo_server:
    image: demo_server
    container_name: demo_server
    build:
      dockerfile: Dockerfile.server
      context: .
    ports:
      - 5000:5000

networks:
  default:
    name: demo_network
